-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ/GSAOKiRuDUBrYP
eVIZA5LfZhNz2OEOmobfj2G0HwegCgYIKoZIzj0DAQehRANCAARx/+2A99zxSpGq
VtUkd8ZDWcS6WkVJhaSkueSiWllYkD9gauB03TraeS0bnM7ohKw/czKBquq8GLqc
kitoGrW3
-----END PRIVATE KEY-----